config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users do
    resources :appointments
  end

  resources :doctors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = doctor.new
  end

  def create
    @doctor = Doctor.new(doctors_params)

    if @doctor.save
      redirect_to doctors_path
    else
      render :new
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])

    if @doctor.update(doctors_params)
      redirect_to doctor_path
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def doctors_params
    params.require(:doctor).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(users_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def users_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/doctors/edit.html.erb
<h1>Edit Name</h1>
<%= form_for @doctor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/doctors/index.html.erb
<h1>List of Doctors</h1>
<p>Click a doctor to see their current appointments or leave a review.</p>
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Doctors#new</h1>
<p>Find me in app/views/doctors/new.html.erb</p>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<p> <%= link_to 'Edit name', edit_doctor_path(@doctor) %></p>
<h2>Appointments</h2>
<ul>
  <% @doctor.appointments.each do |appointment| %>
    <li>
      Patient: <%= appointment.user.name %>
    <br />
    Date and Time: <%= appointment.appointment_date %>
    </li>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Doctors', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit Name</h1>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>View your appointments</h1>
<hr />
<p>Click your name to Login</p>
<p>Not here? <%= link_to 'Register', new_user_path %></p>
<hr />
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Type your name</h1>
<%= form_with(model: @user, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p> <%= link_to 'Edit name', edit_user_path(@user) %></p>
<h2>Appointments</h2>
<ul>
  <% @user.appointments.each do |appointment| %>
    <li>
      Doctor: <%= appointment.doctor.name %>
    <br />
    Date and Time: <%= appointment.appointment_date %>
    </li>
  <% end %>
</ul>